-- Report lifecycle fields (roadmap §11 Stage 2): status, priority, assignment,
-- resolution notes, resolution timestamps. Users submit and read their own
-- reports; lifecycle fields are managed by the (future) admin review workflow,
-- so no user UPDATE policy is added.

alter table public.spoiler_reports
  add column if not exists status text not null default 'new'
    check (status in ('new', 'triaged', 'in_progress', 'resolved', 'dismissed')),
  add column if not exists priority text
    check (priority in ('low', 'medium', 'high')),
  add column if not exists assigned_to uuid references auth.users(id) on delete set null,
  add column if not exists resolution_notes text,
  add column if not exists resolved_at timestamptz;

create table if not exists public.issue_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.topics(id) on delete set null,
  kind text not null default 'other' check (kind in ('bug', 'content', 'other')),
  description text not null,
  context jsonb not null default '{}'::jsonb,
  status text not null default 'new'
    check (status in ('new', 'triaged', 'in_progress', 'resolved', 'dismissed')),
  priority text check (priority in ('low', 'medium', 'high')),
  assigned_to uuid references auth.users(id) on delete set null,
  resolution_notes text,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.issue_reports enable row level security;

drop policy if exists "Users can insert own issue reports" on public.issue_reports;
create policy "Users can insert own issue reports"
on public.issue_reports
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own issue reports" on public.issue_reports;
create policy "Users can read own issue reports"
on public.issue_reports
for select
to authenticated
using (auth.uid() = user_id);

create index if not exists issue_reports_user_created_idx
  on public.issue_reports (user_id, created_at desc);
