create table if not exists public.ai_feedback_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.topics(id) on delete set null,
  source_type text not null check (source_type in ('summary_entry', 'character')),
  source_id text,
  audit_id text,
  source_boundary text,
  source_text_excerpt text,
  feedback_text text not null,
  created_at timestamptz not null default now()
);

alter table public.ai_feedback_reports enable row level security;

drop policy if exists "Users can insert own ai feedback reports" on public.ai_feedback_reports;
create policy "Users can insert own ai feedback reports"
on public.ai_feedback_reports
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own ai feedback reports" on public.ai_feedback_reports;
create policy "Users can read own ai feedback reports"
on public.ai_feedback_reports
for select
to authenticated
using (auth.uid() = user_id);
