alter table if exists public.ai_feedback_reports
add column if not exists audit_id text;

create table if not exists public.ai_generation_audit (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.topics(id) on delete set null,
  source_mode text not null default 'full_update',
  progress_type text,
  lower_boundary integer,
  upper_boundary integer,
  spoiler_boundary text,
  request_payload jsonb not null default '{}'::jsonb,
  summary_debug jsonb not null default '{}'::jsonb,
  characters_debug jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.ai_generation_audit enable row level security;

drop policy if exists "Users can insert own ai generation audit" on public.ai_generation_audit;
create policy "Users can insert own ai generation audit"
on public.ai_generation_audit
for insert
to authenticated
with check (auth.uid() = user_id);

create table if not exists public.ai_generated_artifacts (
  id bigint generated by default as identity primary key,
  audit_id text not null references public.ai_generation_audit(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.topics(id) on delete set null,
  source_type text not null check (source_type in ('summary_entry', 'character')),
  source_id text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_generated_artifacts_lookup
on public.ai_generated_artifacts (user_id, topic_id, source_type, source_id, created_at desc);

alter table public.ai_generated_artifacts enable row level security;

drop policy if exists "Users can insert own ai generated artifacts" on public.ai_generated_artifacts;
create policy "Users can insert own ai generated artifacts"
on public.ai_generated_artifacts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own ai generated artifacts" on public.ai_generated_artifacts;
create policy "Users can read own ai generated artifacts"
on public.ai_generated_artifacts
for select
to authenticated
using (auth.uid() = user_id);
