create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.topics(id) on delete set null,
  event_name text not null,
  event_properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.analytics_events enable row level security;

drop policy if exists "Users can insert own analytics events" on public.analytics_events;
create policy "Users can insert own analytics events"
on public.analytics_events
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own analytics events" on public.analytics_events;
create policy "Users can read own analytics events"
on public.analytics_events
for select
to authenticated
using (auth.uid() = user_id);

create table if not exists public.spoiler_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint references public.topics(id) on delete set null,
  audit_id text,
  boundary_label text,
  summary_excerpt text,
  reason text not null,
  created_at timestamptz not null default now()
);

alter table public.spoiler_reports enable row level security;

drop policy if exists "Users can insert own spoiler reports" on public.spoiler_reports;
create policy "Users can insert own spoiler reports"
on public.spoiler_reports
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own spoiler reports" on public.spoiler_reports;
create policy "Users can read own spoiler reports"
on public.spoiler_reports
for select
to authenticated
using (auth.uid() = user_id);
