-- Interface v2.0 (D-055): entries render as horizontal bookmark ribbons that
-- carry a one-line companion summary instead of the full paragraph. The
-- summary is cached on the row; ai_summary_hash (djb2 of the entry text)
-- detects edits so stale summaries are regenerated by the companion
-- Edge Function's entry_summaries feature. Owner-scoped RLS on entries
-- already covers both columns - the function writes under the user's JWT.
alter table public.entries
  add column if not exists ai_summary text,
  add column if not exists ai_summary_hash text;

comment on column public.entries.ai_summary is
  'One-line companion summary shown on the bookmark ribbon (D-055). Display aid only - never replaces the reader''s text.';
comment on column public.entries.ai_summary_hash is
  'djb2 hash of entries.text when ai_summary was generated; a mismatch marks the summary stale.';
