-- D-062: Reading Fitness layer (September 2026 beta feedback). Adds the
-- Sandglass timer's session log, favorite/reflection columns for the Quotes
-- tab, and a reader-set difficulty override. Every metric (Difficulty,
-- Reading Fitness, streaks, trophies) is derived on-device from these rows
-- plus existing entries - no provider call and no server-side aggregation
-- (docs/READING_METRICS.md). Social features stay deferred.

-- 1. Reading sessions: one row per completed Sandglass session.
create table if not exists public.reading_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint not null references public.topics(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  duration_seconds integer not null check (duration_seconds > 0),
  planned_seconds integer check (planned_seconds is null or planned_seconds > 0),
  start_page integer check (start_page is null or start_page >= 0),
  end_page integer check (end_page is null or end_page >= 0),
  pages_read integer check (pages_read is null or pages_read >= 0),
  created_at timestamptz not null default now(),
  constraint reading_sessions_ends_after_start check (ended_at >= started_at)
);

create index if not exists reading_sessions_user_started_idx
  on public.reading_sessions (user_id, started_at desc);
create index if not exists reading_sessions_topic_idx
  on public.reading_sessions (topic_id);

alter table public.reading_sessions enable row level security;

drop policy if exists "reading_sessions_select_own" on public.reading_sessions;
create policy "reading_sessions_select_own" on public.reading_sessions
  for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "reading_sessions_insert_own" on public.reading_sessions;
create policy "reading_sessions_insert_own" on public.reading_sessions
  for insert to authenticated
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.topics t
      where t.id = topic_id and t.user_id = auth.uid()
    )
  );

drop policy if exists "reading_sessions_update_own" on public.reading_sessions;
create policy "reading_sessions_update_own" on public.reading_sessions
  for update to authenticated
  using (auth.uid() = user_id)
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.topics t
      where t.id = topic_id and t.user_id = auth.uid()
    )
  );

drop policy if exists "reading_sessions_delete_own" on public.reading_sessions;
create policy "reading_sessions_delete_own" on public.reading_sessions
  for delete to authenticated
  using (auth.uid() = user_id);

revoke all on table public.reading_sessions from anon;
grant select, insert, update, delete on table public.reading_sessions to authenticated;
grant all on table public.reading_sessions to service_role;

-- 2. Quotes tab: favorites and the reader's own reflection on a quote.
-- Additive, defaulted columns - existing clients keep working unchanged.
alter table public.entries
  add column if not exists is_favorite boolean not null default false,
  add column if not exists reflection text;

create index if not exists entries_user_favorite_idx
  on public.entries (user_id)
  where is_favorite;

-- 3. Difficulty override: the reader's 1-10 rating wins over the computed
-- Text Difficulty Index (feedback asked for editable difficulty tags).
alter table public.topics
  add column if not exists difficulty_override numeric(3,1)
  check (difficulty_override is null or (difficulty_override >= 1 and difficulty_override <= 10));

-- Export/delete-account coverage: the account deletion function removes
-- auth.users, and reading_sessions cascades from it.
