-- Stage 4 Phase 1 (STAGE_4_BUILD_PLAN.md): server-authoritative companion
-- entitlements, per-feature usage quotas, session auditing, the conversation
-- store, and the genre column feeding the mascot archetype (D-038).
-- Roadmap section 13; D-012 rigor: no client-only entitlement decisions.

-- 1. Entitlements: the server-authoritative subscription/trial/comp state.
-- The owner can read their own row (the client renders offer vs. active
-- states from it); every write happens through the service role (billing
-- webhooks in Phase 3, dev comps until then).
create table if not exists public.companion_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null default 'none'
    check (status in ('none', 'comped', 'trial', 'active', 'expired', 'canceled')),
  source text not null default 'none'
    check (source in ('none', 'dev_comp', 'trial', 'app_store', 'play_store')),
  trial_started_at timestamptz,
  trial_expires_at timestamptz,
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.companion_entitlements enable row level security;

drop policy if exists "Users can read own companion entitlement" on public.companion_entitlements;
create policy "Users can read own companion entitlement"
on public.companion_entitlements
for select
to authenticated
using (auth.uid() = user_id);

revoke all on table public.companion_entitlements from anon, authenticated;
grant select on table public.companion_entitlements to authenticated;
grant all on table public.companion_entitlements to service_role;

-- Development comp (Phase 1): existing accounts are comped so the companion
-- is fully testable before billing exists. New signups start unentitled and
-- see the subscription offer, which is exactly the Phase 3 test surface.
insert into public.companion_entitlements (user_id, status, source)
select id, 'comped', 'dev_comp'
from auth.users
on conflict (user_id) do nothing;

-- 2. Usage events double as the companion session audit (roadmap section 13:
-- entitlement decision, feature, quota outcome, provider cost, latency, and
-- grounding source counts - never entry content). Service-role only.
create table if not exists public.companion_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  audit_id text,
  feature text not null check (feature in (
    'dialogue', 'recap', 'quiz', 'cue_cards', 'club_prep',
    'word_bank', 'structuring', 'event_flags', 'search'
  )),
  status text not null default 'started'
    check (status in ('started', 'succeeded', 'failed', 'rate_limited', 'denied')),
  entitlement_decision text not null default 'allowed'
    check (entitlement_decision in ('allowed', 'denied_unentitled', 'denied_quota')),
  quota_scope text check (quota_scope is null or quota_scope in ('user', 'project')),
  topic_id bigint references public.topics(id) on delete set null,
  model text,
  prompt_tokens integer check (prompt_tokens is null or prompt_tokens >= 0),
  output_tokens integer check (output_tokens is null or output_tokens >= 0),
  grounding_entries integer check (grounding_entries is null or grounding_entries >= 0),
  grounding_characters integer check (grounding_characters is null or grounding_characters >= 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  http_status integer check (http_status is null or http_status between 100 and 599),
  upstream_status integer check (upstream_status is null or upstream_status between 100 and 599),
  error_code text,
  error_message text
);

create index if not exists idx_companion_usage_user_feature_started
on public.companion_usage_events (user_id, feature, started_at desc);

create index if not exists idx_companion_usage_started
on public.companion_usage_events (started_at desc);

alter table public.companion_usage_events enable row level security;

revoke all on table public.companion_usage_events from anon, authenticated;
grant all on table public.companion_usage_events to service_role;

-- Per-feature daily quota consumption, serialized with advisory locks so
-- simultaneous requests cannot bypass either cap (same pattern as the
-- proven consume_ai_daily_quota from Stage 1). Denied and rate-limited
-- events never count against quota; only started/succeeded/failed do.
create or replace function public.consume_companion_quota(
  p_user_id uuid,
  p_feature text,
  p_audit_id text,
  p_topic_id bigint,
  p_user_daily_limit integer,
  p_project_daily_limit integer
)
returns table (
  allowed boolean,
  quota_scope text,
  user_used integer,
  user_remaining integer,
  user_limit integer,
  project_used integer,
  project_remaining integer,
  project_limit integer,
  reset_at timestamptz,
  event_id bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_window_start timestamptz := date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  v_reset_at timestamptz;
  v_user_limit integer := greatest(1, least(coalesce(p_user_daily_limit, 50), 1000));
  v_project_limit integer := greatest(1, least(coalesce(p_project_daily_limit, 1000), 100000));
  v_user_used integer := 0;
  v_project_used integer := 0;
  v_event_id bigint;
begin
  if p_user_id is null then
    raise exception 'Authenticated user is required';
  end if;

  if p_feature not in (
    'dialogue', 'recap', 'quiz', 'cue_cards', 'club_prep',
    'word_bank', 'structuring', 'event_flags', 'search'
  ) then
    raise exception 'Invalid companion feature';
  end if;

  v_reset_at := v_window_start + interval '1 day';

  perform pg_advisory_xact_lock(hashtextextended('companion-project:' || v_window_start::text, 0));
  perform pg_advisory_xact_lock(hashtextextended('companion-user:' || p_user_id::text || ':' || v_window_start::text, 0));

  select count(*)::integer
  into v_project_used
  from public.companion_usage_events
  where started_at >= v_window_start
    and started_at < v_reset_at
    and status in ('started', 'succeeded', 'failed');

  select count(*)::integer
  into v_user_used
  from public.companion_usage_events
  where user_id = p_user_id
    and feature = p_feature
    and started_at >= v_window_start
    and started_at < v_reset_at
    and status in ('started', 'succeeded', 'failed');

  if v_project_used >= v_project_limit then
    insert into public.companion_usage_events (
      user_id, audit_id, feature, status, entitlement_decision, quota_scope,
      topic_id, completed_at, duration_ms, http_status, error_code, error_message
    ) values (
      p_user_id, p_audit_id, p_feature, 'rate_limited', 'denied_quota', 'project',
      p_topic_id, now(), 0, 429, 'COMPANION_PROJECT_DAILY_LIMIT_EXCEEDED',
      'Project daily companion limit reached.'
    ) returning id into v_event_id;

    return query select
      false, 'project'::text, v_user_used, greatest(0, v_user_limit - v_user_used), v_user_limit,
      v_project_used, 0, v_project_limit, v_reset_at, v_event_id;
    return;
  end if;

  if v_user_used >= v_user_limit then
    insert into public.companion_usage_events (
      user_id, audit_id, feature, status, entitlement_decision, quota_scope,
      topic_id, completed_at, duration_ms, http_status, error_code, error_message
    ) values (
      p_user_id, p_audit_id, p_feature, 'rate_limited', 'denied_quota', 'user',
      p_topic_id, now(), 0, 429, 'COMPANION_DAILY_LIMIT_EXCEEDED',
      'User daily companion feature limit reached.'
    ) returning id into v_event_id;

    return query select
      false, 'user'::text, v_user_used, 0, v_user_limit,
      v_project_used, greatest(0, v_project_limit - v_project_used), v_project_limit,
      v_reset_at, v_event_id;
    return;
  end if;

  insert into public.companion_usage_events (
    user_id, audit_id, feature, status, entitlement_decision, quota_scope, topic_id
  )
  values (p_user_id, p_audit_id, p_feature, 'started', 'allowed', 'user', p_topic_id)
  returning id into v_event_id;

  v_user_used := v_user_used + 1;
  v_project_used := v_project_used + 1;

  return query select
    true, 'user'::text, v_user_used, greatest(0, v_user_limit - v_user_used), v_user_limit,
    v_project_used, greatest(0, v_project_limit - v_project_used), v_project_limit,
    v_reset_at, v_event_id;
end;
$$;

revoke all on function public.consume_companion_quota(uuid, text, text, bigint, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_companion_quota(uuid, text, text, bigint, integer, integer) to service_role;

-- 3. Conversation store: the companion remembers past dialogue per book.
-- User-owned rows under RLS; inserts require ownership of the referenced
-- book (the D-041 topic-ownership rule). The transcript is immutable - no
-- update policy - and deletable by its owner.
create table if not exists public.companion_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_id bigint not null references public.topics(id) on delete cascade,
  role text not null check (role in ('reader', 'companion')),
  feature text not null default 'dialogue' check (feature in (
    'dialogue', 'recap', 'quiz', 'cue_cards', 'club_prep', 'word_bank', 'structuring'
  )),
  content text not null check (char_length(content) between 1 and 20000),
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_companion_messages_book
on public.companion_messages (user_id, topic_id, created_at);

alter table public.companion_messages enable row level security;

drop policy if exists "Users can read own companion messages" on public.companion_messages;
create policy "Users can read own companion messages"
on public.companion_messages
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own companion messages" on public.companion_messages;
create policy "Users can insert own companion messages"
on public.companion_messages
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.topics t
    where t.id = topic_id and t.user_id = auth.uid()
  )
);

drop policy if exists "Users can delete own companion messages" on public.companion_messages;
create policy "Users can delete own companion messages"
on public.companion_messages
for delete
to authenticated
using (auth.uid() = user_id);

-- 4. Genre feeds the intellectual-archetype profile (D-038). Filled from
-- Google Books categories on add going forward; null is fine (the archetype
-- falls back to the balanced scholar).
alter table public.topics add column if not exists genre text;
