create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  audit_id text,
  mode text not null check (mode in ('summary', 'characters', 'locations', 'full_update')),
  status text not null default 'started' check (status in ('started', 'succeeded', 'failed', 'rate_limited')),
  quota_scope text check (quota_scope is null or quota_scope in ('user', 'project')),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  http_status integer check (http_status is null or http_status between 100 and 599),
  upstream_status integer check (upstream_status is null or upstream_status between 100 and 599),
  error_code text,
  error_message text
);

create index if not exists idx_ai_usage_events_user_started
on public.ai_usage_events (user_id, started_at desc);

create index if not exists idx_ai_usage_events_started
on public.ai_usage_events (started_at desc);

alter table public.ai_usage_events enable row level security;

-- Usage records are internal operational data. Only the Edge Function service role can access them.
revoke all on table public.ai_usage_events from anon, authenticated;
grant all on table public.ai_usage_events to service_role;

create or replace function public.consume_ai_daily_quota(
  p_user_id uuid,
  p_mode text,
  p_audit_id text,
  p_user_daily_limit integer,
  p_project_daily_limit integer
)
returns table (
  allowed boolean,
  quota_scope text,
  user_used integer,
  user_remaining integer,
  user_limit integer,
  project_used integer,
  project_remaining integer,
  project_limit integer,
  reset_at timestamptz,
  event_id bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_window_start timestamptz := date_trunc('day', now() at time zone 'utc') at time zone 'utc';
  v_reset_at timestamptz;
  v_user_limit integer := greatest(1, least(coalesce(p_user_daily_limit, 30), 500));
  v_project_limit integer := greatest(1, least(coalesce(p_project_daily_limit, 500), 100000));
  v_user_used integer := 0;
  v_project_used integer := 0;
  v_event_id bigint;
begin
  if p_user_id is null then
    raise exception 'Authenticated user is required';
  end if;

  if p_mode not in ('summary', 'characters', 'locations', 'full_update') then
    raise exception 'Invalid AI mode';
  end if;

  v_reset_at := v_window_start + interval '1 day';

  -- Serialize project and user counters so simultaneous requests cannot bypass either cap.
  perform pg_advisory_xact_lock(hashtextextended('ai-project:' || v_window_start::text, 0));
  perform pg_advisory_xact_lock(hashtextextended('ai-user:' || p_user_id::text || ':' || v_window_start::text, 0));

  select count(*)::integer
  into v_project_used
  from public.ai_usage_events
  where started_at >= v_window_start
    and started_at < v_reset_at
    and status in ('started', 'succeeded', 'failed');

  select count(*)::integer
  into v_user_used
  from public.ai_usage_events
  where user_id = p_user_id
    and started_at >= v_window_start
    and started_at < v_reset_at
    and status in ('started', 'succeeded', 'failed');

  if v_project_used >= v_project_limit then
    insert into public.ai_usage_events (
      user_id, audit_id, mode, status, quota_scope, completed_at,
      duration_ms, http_status, error_code, error_message
    ) values (
      p_user_id, p_audit_id, p_mode, 'rate_limited', 'project', now(),
      0, 429, 'AI_PROJECT_DAILY_LIMIT_EXCEEDED', 'Project daily AI limit reached.'
    ) returning id into v_event_id;

    return query select
      false, 'project'::text, v_user_used, greatest(0, v_user_limit - v_user_used), v_user_limit,
      v_project_used, 0, v_project_limit, v_reset_at, v_event_id;
    return;
  end if;

  if v_user_used >= v_user_limit then
    insert into public.ai_usage_events (
      user_id, audit_id, mode, status, quota_scope, completed_at,
      duration_ms, http_status, error_code, error_message
    ) values (
      p_user_id, p_audit_id, p_mode, 'rate_limited', 'user', now(),
      0, 429, 'AI_DAILY_LIMIT_EXCEEDED', 'User daily AI limit reached.'
    ) returning id into v_event_id;

    return query select
      false, 'user'::text, v_user_used, 0, v_user_limit,
      v_project_used, greatest(0, v_project_limit - v_project_used), v_project_limit,
      v_reset_at, v_event_id;
    return;
  end if;

  insert into public.ai_usage_events (user_id, audit_id, mode, status, quota_scope)
  values (p_user_id, p_audit_id, p_mode, 'started', 'user')
  returning id into v_event_id;

  v_user_used := v_user_used + 1;
  v_project_used := v_project_used + 1;

  return query select
    true, 'user'::text, v_user_used, greatest(0, v_user_limit - v_user_used), v_user_limit,
    v_project_used, greatest(0, v_project_limit - v_project_used), v_project_limit,
    v_reset_at, v_event_id;
end;
$$;

revoke all on function public.consume_ai_daily_quota(uuid, text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_ai_daily_quota(uuid, text, text, integer, integer) to service_role;

create or replace view public.ai_usage_daily_summary
with (security_invoker = true)
as
select
  (started_at at time zone 'utc')::date as usage_date,
  mode,
  count(*) filter (where status in ('started', 'succeeded', 'failed')) as generations,
  count(*) filter (where status = 'succeeded') as succeeded,
  count(*) filter (where status = 'failed') as failed,
  count(*) filter (where status = 'rate_limited') as blocked,
  count(distinct user_id) as active_users,
  round(avg(duration_ms) filter (where duration_ms is not null))::integer as average_duration_ms,
  round((percentile_cont(0.95) within group (order by duration_ms)
    filter (where duration_ms is not null))::numeric)::integer as p95_duration_ms
from public.ai_usage_events
group by (started_at at time zone 'utc')::date, mode;

create or replace view public.ai_usage_user_daily_summary
with (security_invoker = true)
as
select
  (started_at at time zone 'utc')::date as usage_date,
  user_id,
  count(*) filter (where status in ('started', 'succeeded', 'failed')) as generations,
  count(*) filter (where status = 'succeeded') as succeeded,
  count(*) filter (where status = 'failed') as failed,
  count(*) filter (where status = 'rate_limited') as blocked,
  round(avg(duration_ms) filter (where duration_ms is not null))::integer as average_duration_ms
from public.ai_usage_events
group by (started_at at time zone 'utc')::date, user_id;

revoke all on public.ai_usage_daily_summary from public, anon, authenticated;
revoke all on public.ai_usage_user_daily_summary from public, anon, authenticated;
grant select on public.ai_usage_daily_summary to service_role;
grant select on public.ai_usage_user_daily_summary to service_role;
